#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
typedef long int mpfr_prec_t; typedef long int mpfr_exp_t; typedef unsigned long int mp_limb_t;
typedef struct { mpfr_prec_t _mpfr_prec; int _mpfr_sign; mpfr_exp_t _mpfr_exp; mp_limb_t *_mpfr_d; } __mpfr_struct;
typedef __mpfr_struct *mpfr_ptr; typedef const __mpfr_struct *mpfr_srcptr; typedef __mpfr_struct mpfr_t[1];
typedef enum { MPFR_RNDN=0,MPFR_RNDZ=1,MPFR_RNDU=2,MPFR_RNDD=3,MPFR_RNDA=4 } mpfr_rnd_t;
extern void mpfr_init2(mpfr_ptr,mpfr_prec_t); extern int mpfr_set(mpfr_ptr,mpfr_srcptr,mpfr_rnd_t); extern void mpfr_clear(mpfr_ptr); extern int mpfr_set_str(mpfr_ptr,const char*,int,mpfr_rnd_t); extern int mpfr_set_ui(mpfr_ptr,unsigned long,mpfr_rnd_t); extern int mpfr_add(mpfr_ptr,mpfr_srcptr,mpfr_srcptr,mpfr_rnd_t); extern int mpfr_add_ui(mpfr_ptr,mpfr_srcptr,unsigned long,mpfr_rnd_t); extern int mpfr_sub(mpfr_ptr,mpfr_srcptr,mpfr_srcptr,mpfr_rnd_t); extern int mpfr_mul(mpfr_ptr,mpfr_srcptr,mpfr_srcptr,mpfr_rnd_t); extern int mpfr_div(mpfr_ptr,mpfr_srcptr,mpfr_srcptr,mpfr_rnd_t); extern int mpfr_sqr(mpfr_ptr,mpfr_srcptr,mpfr_rnd_t); extern int mpfr_sqrt(mpfr_ptr,mpfr_srcptr,mpfr_rnd_t); extern int mpfr_log(mpfr_ptr,mpfr_srcptr,mpfr_rnd_t); extern int mpfr_exp(mpfr_ptr,mpfr_srcptr,mpfr_rnd_t); extern int mpfr_expm1(mpfr_ptr,mpfr_srcptr,mpfr_rnd_t); extern int mpfr_cmp(mpfr_srcptr,mpfr_srcptr); extern int mpfr_cmp_ui(mpfr_srcptr,unsigned long); extern double mpfr_get_d(mpfr_srcptr,mpfr_rnd_t);
#ifndef PREC
#define PREC 512
#endif
#ifndef K
#define K 2048
#endif
#ifndef LBASE
#define LBASE 619
#endif
#ifndef LDEN
#define LDEN 100
#endif
#ifndef LCOUNT
#define LCOUNT 85
#endif
#ifndef ILO
#define ILO 0
#endif
#ifndef IHI
#define IHI 32
#endif
static void I(mpfr_t x){mpfr_init2(x,PREC);} static void Z(mpfr_t x){mpfr_set_ui(x,0,MPFR_RNDN);} static void S(mpfr_t x,const char*s,mpfr_rnd_t r){mpfr_set_str(x,s,10,r);} static void NEG(mpfr_t r,mpfr_t a,mpfr_rnd_t rnd){mpfr_t z;I(z);Z(z);mpfr_sub(r,z,a,rnd);mpfr_clear(z);} static void RAT(mpfr_t x,unsigned long n,unsigned long d,mpfr_rnd_t r){mpfr_t a,b;I(a);I(b);mpfr_set_ui(a,n,MPFR_RNDN);mpfr_set_ui(b,d,MPFR_RNDN);mpfr_div(x,a,b,r);mpfr_clear(a);mpfr_clear(b);} 
static mpfr_t lnlo[K+1],lnhi[K+1];
static void init_logs(void){for(int n=0;n<=K;n++){I(lnlo[n]);I(lnhi[n]);if(n>=2){mpfr_t a;I(a);mpfr_set_ui(a,n,MPFR_RNDN);mpfr_log(lnlo[n],a,MPFR_RNDD);mpfr_log(lnhi[n],a,MPFR_RNDU);mpfr_clear(a);}}}
static void exprel_up(mpfr_t out,mpfr_t z){mpfr_t eps,neps,tmp,num,den,one;I(eps);I(neps);I(tmp);I(num);I(den);I(one);S(eps,"0.001",MPFR_RNDN);NEG(neps,eps,MPFR_RNDN);mpfr_set_ui(one,1,MPFR_RNDN);if(mpfr_cmp(z,eps)<=0&&mpfr_cmp(z,neps)>=0){mpfr_exp(out,eps,MPFR_RNDU);}else if(mpfr_cmp_ui(z,0)>0){mpfr_expm1(num,z,MPFR_RNDU);mpfr_div(out,num,z,MPFR_RNDU);}else{mpfr_exp(tmp,z,MPFR_RNDD);mpfr_sub(num,one,tmp,MPFR_RNDU);NEG(den,z,MPFR_RNDN);mpfr_div(out,num,den,MPFR_RNDU);}mpfr_clear(eps);mpfr_clear(neps);mpfr_clear(tmp);mpfr_clear(num);mpfr_clear(den);mpfr_clear(one);}
static void theta_up(mpfr_t out,mpfr_t z){mpfr_t eps,neps,one,tmp,tmp2,num,den,a;I(eps);I(neps);I(one);I(tmp);I(tmp2);I(num);I(den);I(a);S(eps,"0.001",MPFR_RNDN);NEG(neps,eps,MPFR_RNDN);mpfr_set_ui(one,1,MPFR_RNDN);if(mpfr_cmp(z,eps)<=0&&mpfr_cmp(z,neps)>=0){mpfr_exp(tmp,eps,MPFR_RNDU);S(tmp2,"0.5",MPFR_RNDU);mpfr_mul(out,tmp,tmp2,MPFR_RNDU);}else if(mpfr_cmp_ui(z,0)>0){if(mpfr_cmp(z,one)<0){mpfr_sub(tmp,one,z,MPFR_RNDD);mpfr_exp(tmp2,z,MPFR_RNDD);mpfr_mul(tmp,tmp,tmp2,MPFR_RNDD);mpfr_sub(num,one,tmp,MPFR_RNDU);}else{mpfr_sub(tmp,z,one,MPFR_RNDU);mpfr_exp(tmp2,z,MPFR_RNDU);mpfr_mul(tmp,tmp,tmp2,MPFR_RNDU);mpfr_add_ui(num,tmp,1,MPFR_RNDU);}mpfr_sqr(den,z,MPFR_RNDD);mpfr_div(out,num,den,MPFR_RNDU);}else{NEG(a,z,MPFR_RNDN);mpfr_add_ui(tmp,a,1,MPFR_RNDD);mpfr_exp(tmp2,z,MPFR_RNDD);mpfr_mul(tmp,tmp,tmp2,MPFR_RNDD);mpfr_sub(num,one,tmp,MPFR_RNDU);mpfr_sqr(den,a,MPFR_RNDD);mpfr_div(out,num,den,MPFR_RNDU);}mpfr_clear(eps);mpfr_clear(neps);mpfr_clear(one);mpfr_clear(tmp);mpfr_clear(tmp2);mpfr_clear(num);mpfr_clear(den);mpfr_clear(a);}
static void g1_up(mpfr_t out,mpfr_t v,mpfr_t tb,mpfr_t c){mpfr_t a,b,f;I(a);I(b);I(f);mpfr_set_ui(f,4,MPFR_RNDN);mpfr_sqr(a,v,MPFR_RNDU);mpfr_mul(a,a,tb,MPFR_RNDU);mpfr_div(a,a,f,MPFR_RNDU);mpfr_mul(b,c,v,MPFR_RNDD);mpfr_sub(out,a,b,MPFR_RNDU);mpfr_clear(a);mpfr_clear(b);mpfr_clear(f);}
static void chord(mpfr_t I0,mpfr_t I1,mpfr_t a,mpfr_t b,mpfr_t gA,mpfr_t gB){mpfr_t D,de,xr,th,eg,t,t2;I(D);I(de);I(xr);I(th);I(eg);I(t);I(t2);mpfr_sub(D,b,a,MPFR_RNDU);mpfr_sub(de,gB,gA,MPFR_RNDU);exprel_up(xr,de);theta_up(th,de);mpfr_exp(eg,gA,MPFR_RNDU);mpfr_mul(t,D,eg,MPFR_RNDU);mpfr_mul(I0,t,xr,MPFR_RNDU);mpfr_mul(t,a,D,MPFR_RNDU);mpfr_mul(t,t,xr,MPFR_RNDU);mpfr_sqr(t2,D,MPFR_RNDU);mpfr_mul(t2,t2,th,MPFR_RNDU);mpfr_add(t,t,t2,MPFR_RNDU);mpfr_mul(I1,eg,t,MPFR_RNDU);mpfr_clear(D);mpfr_clear(de);mpfr_clear(xr);mpfr_clear(th);mpfr_clear(eg);mpfr_clear(t);mpfr_clear(t2);}
static void expseg(mpfr_t I0,mpfr_t I1,mpfr_t a,mpfr_t b,mpfr_t rate){mpfr_t inv,inv2,ra,rb,ea,eb,Ta,Tb,t;I(inv);I(inv2);I(ra);I(rb);I(ea);I(eb);I(Ta);I(Tb);I(t);mpfr_set_ui(t,1,MPFR_RNDN);mpfr_div(inv,t,rate,MPFR_RNDU);mpfr_sqr(inv2,inv,MPFR_RNDU);mpfr_mul(ra,rate,a,MPFR_RNDD);NEG(ra,ra,MPFR_RNDU);mpfr_exp(ea,ra,MPFR_RNDU);mpfr_mul(rb,rate,b,MPFR_RNDU);NEG(rb,rb,MPFR_RNDD);mpfr_exp(eb,rb,MPFR_RNDD);mpfr_sub(t,ea,eb,MPFR_RNDU);mpfr_mul(I0,t,inv,MPFR_RNDU);mpfr_mul(Ta,a,inv,MPFR_RNDU);mpfr_add(Ta,Ta,inv2,MPFR_RNDU);mpfr_mul(Ta,Ta,ea,MPFR_RNDU);{mpfr_t il,i2l;I(il);I(i2l);mpfr_set_ui(t,1,MPFR_RNDN);mpfr_div(il,t,rate,MPFR_RNDD);mpfr_sqr(i2l,il,MPFR_RNDD);mpfr_mul(Tb,b,il,MPFR_RNDD);mpfr_add(Tb,Tb,i2l,MPFR_RNDD);mpfr_mul(Tb,Tb,eb,MPFR_RNDD);mpfr_clear(il);mpfr_clear(i2l);}mpfr_sub(I1,Ta,Tb,MPFR_RNDU);mpfr_clear(inv);mpfr_clear(inv2);mpfr_clear(ra);mpfr_clear(rb);mpfr_clear(ea);mpfr_clear(eb);mpfr_clear(Ta);mpfr_clear(Tb);mpfr_clear(t);}
static void tbox(int i,mpfr_t ta,mpfr_t tb){if(i<18){RAT(ta,i,100,MPFR_RNDD);RAT(tb,i+1,100,MPFR_RNDU);}else if(i<24){int k=i-18;RAT(ta,180+5*k,1000,MPFR_RNDD);RAT(tb,185+5*k,1000,MPFR_RNDU);}else if(i<28){int k=i-24;RAT(ta,210+2*k,1000,MPFR_RNDD);RAT(tb,212+2*k,1000,MPFR_RNDU);}else{int k=i-28;RAT(ta,436+k,2000,MPFR_RNDD);RAT(tb,437+k,2000,MPFR_RNDU);}}
static double tlo(int i){if(i<18)return i/100.;if(i<24)return(180+5*(i-18))/1000.;if(i<28)return(210+2*(i-24))/1000.;return(436+i-28)/2000.;}
static double thi(int i){if(i<18)return(i+1)/100.;if(i<24)return(185+5*(i-18))/1000.;if(i<28)return(212+2*(i-24))/1000.;return(437+i-28)/2000.;}
static int eval(int ti,int lj,mpfr_t margin,mpfr_t A0,mpfr_t A1){
 mpfr_t ta,tb,la,lb,eps,del,eta,phead,pI,cI,q,rate,r,u1,u2,u3,gA,gB,H0,H1,T0,T1,t,t2,w,I0,I1,Phi,S0,E0,E1,d,half,rad,Y,lhs,one,two,four;
 mpfr_t *v[]={&ta,&tb,&la,&lb,&eps,&del,&eta,&phead,&pI,&cI,&q,&rate,&r,&u1,&u2,&u3,&gA,&gB,&H0,&H1,&T0,&T1,&t,&t2,&w,&I0,&I1,&Phi,&S0,&E0,&E1,&d,&half,&rad,&Y,&lhs,&one,&two,&four};for(size_t i=0;i<sizeof(v)/sizeof(v[0]);i++)I(*v[i]);mpfr_set_ui(one,1,MPFR_RNDN);mpfr_set_ui(two,2,MPFR_RNDN);mpfr_set_ui(four,4,MPFR_RNDN);tbox(ti,ta,tb);RAT(la,LBASE+lj,LDEN,MPFR_RNDD);RAT(lb,LBASE+lj+1,LDEN,MPFR_RNDU);S(eps,"0.0000000001",MPFR_RNDU);S(del,"0.000002",MPFR_RNDU);
 S(phead,"0.5",MPFR_RNDD);mpfr_div(t,la,four,MPFR_RNDD);mpfr_add(phead,phead,t,MPFR_RNDD);mpfr_sub(phead,phead,eps,MPFR_RNDD);mpfr_div(eta,del,four,MPFR_RNDU);mpfr_add(eta,eta,eps,MPFR_RNDU);S(pI,"0.5",MPFR_RNDD);mpfr_div(t,la,four,MPFR_RNDD);mpfr_add(pI,pI,t,MPFR_RNDD);mpfr_sub(pI,pI,eta,MPFR_RNDD);mpfr_sub(cI,pI,one,MPFR_RNDD);S(q,"0.5",MPFR_RNDD);mpfr_set_ui(t,8,MPFR_RNDN);mpfr_div(t,la,t,MPFR_RNDD);mpfr_add(q,q,t,MPFR_RNDD);mpfr_sub(q,q,eta,MPFR_RNDD);mpfr_sub(rate,q,one,MPFR_RNDD);
 Z(H0);Z(H1);for(int n=2;n<=K;n++){mpfr_sqr(t,lnhi[n],MPFR_RNDU);mpfr_mul(t,t,tb,MPFR_RNDU);mpfr_div(t,t,four,MPFR_RNDU);mpfr_mul(t2,phead,lnlo[n],MPFR_RNDD);mpfr_sub(t,t,t2,MPFR_RNDU);mpfr_exp(w,t,MPFR_RNDU);mpfr_add(H0,H0,w,MPFR_RNDU);mpfr_mul(t,w,lnhi[n],MPFR_RNDU);mpfr_add(H1,H1,t,MPFR_RNDU);}mpfr_set_ui(t,K,MPFR_RNDN);mpfr_log(r,t,MPFR_RNDD);
 {mpfr_t laU,tbL;I(laU);I(tbL);RAT(laU,LBASE+lj,LDEN,MPFR_RNDU);tbox(ti,t,tbL);mpfr_mul(t,two,tbL,MPFR_RNDD);mpfr_div(u1,laU,t,MPFR_RNDU);mpfr_clear(laU);mpfr_clear(tbL);}g1_up(gA,r,tb,cI);g1_up(gB,u1,tb,cI);chord(I0,I1,r,u1,gA,gB);mpfr_add(T0,H0,I0,MPFR_RNDU);mpfr_add(T1,H1,I1,MPFR_RNDU);
 if(ti==0){mpfr_t ea,inv,inv2;I(ea);I(inv);I(inv2);mpfr_mul(t,rate,u1,MPFR_RNDD);NEG(t,t,MPFR_RNDU);mpfr_exp(ea,t,MPFR_RNDU);mpfr_div(inv,one,rate,MPFR_RNDU);mpfr_sqr(inv2,inv,MPFR_RNDU);mpfr_mul(t,ea,inv,MPFR_RNDU);mpfr_add(T0,T0,t,MPFR_RNDU);mpfr_mul(t,u1,inv,MPFR_RNDU);mpfr_add(t,t,inv2,MPFR_RNDU);mpfr_mul(t,t,ea,MPFR_RNDU);mpfr_add(T1,T1,t,MPFR_RNDU);mpfr_clear(ea);mpfr_clear(inv);mpfr_clear(inv2);}else{mpfr_t laU;I(laU);RAT(laU,LBASE+lj,LDEN,MPFR_RNDU);mpfr_mul(t,two,ta,MPFR_RNDD);mpfr_div(u2,laU,t,MPFR_RNDU);expseg(I0,I1,u1,u2,rate);mpfr_add(T0,T0,I0,MPFR_RNDU);mpfr_add(T1,T1,I1,MPFR_RNDU);mpfr_add(t,lb,del,MPFR_RNDU);mpfr_mul(t2,two,ta,MPFR_RNDD);mpfr_div(u3,t,t2,MPFR_RNDU);if(mpfr_cmp(u3,u2)>0){mpfr_t D,g,eg;I(D);I(g);I(eg);mpfr_sub(D,u3,u2,MPFR_RNDU);S(t,"0.5",MPFR_RNDU);mpfr_add(t,t,eta,MPFR_RNDU);mpfr_mul(t,t,u2,MPFR_RNDU);mpfr_sqr(t2,u2,MPFR_RNDU);mpfr_mul(t2,t2,ta,MPFR_RNDD);mpfr_div(t2,t2,four,MPFR_RNDD);mpfr_sub(g,t,t2,MPFR_RNDU);mpfr_exp(eg,g,MPFR_RNDU);mpfr_mul(I0,eg,D,MPFR_RNDU);mpfr_add(T0,T0,I0,MPFR_RNDU);mpfr_mul(t,u2,D,MPFR_RNDU);mpfr_sqr(t2,D,MPFR_RNDU);mpfr_div(t2,t2,two,MPFR_RNDU);mpfr_add(t,t,t2,MPFR_RNDU);mpfr_mul(I1,eg,t,MPFR_RNDU);mpfr_add(T1,T1,I1,MPFR_RNDU);mpfr_clear(D);mpfr_clear(g);mpfr_clear(eg);}mpfr_clear(laU);}
 S(E0,"0.001",MPFR_RNDU);S(E1,"0.02",MPFR_RNDU);S(d,"0.501",MPFR_RNDU);mpfr_div(t,la,tb,MPFR_RNDD);mpfr_div(Phi,t,four,MPFR_RNDD);S(t,"0.000001",MPFR_RNDU);mpfr_sub(Phi,Phi,t,MPFR_RNDD);mpfr_sub(S0,one,T0,MPFR_RNDD);mpfr_div(half,E0,two,MPFR_RNDU);mpfr_sqr(rad,S0,MPFR_RNDD);mpfr_sqr(t,half,MPFR_RNDU);mpfr_sub(rad,rad,t,MPFR_RNDD);int ok=mpfr_cmp(S0,half)>0&&mpfr_cmp_ui(rad,0)>0;if(ok){mpfr_sqrt(Y,rad,MPFR_RNDD);mpfr_mul(lhs,Phi,Y,MPFR_RNDD);mpfr_mul(t,d,T1,MPFR_RNDU);mpfr_sub(lhs,lhs,t,MPFR_RNDD);mpfr_mul(lhs,lhs,two,MPFR_RNDD);mpfr_sub(margin,lhs,E1,MPFR_RNDD);}else S(margin,"-100",MPFR_RNDD);mpfr_set(A0,T0,MPFR_RNDU);mpfr_set(A1,T1,MPFR_RNDU);for(size_t i=0;i<sizeof(v)/sizeof(v[0]);i++)mpfr_clear(*v[i]);return ok;
}
int main(void){init_logs();mpfr_t minm,m,A0,A1;I(minm);I(m);I(A0);I(A1);S(minm,"1000",MPFR_RNDN);int mi=-1,mj=-1,fail=0;double wa=0,wb=0;for(int i=ILO;i<IHI;i++)for(int j=0;j<LCOUNT;j++){int ok=eval(i,j,m,A0,A1);if(!ok||mpfr_cmp_ui(m,0)<=0)fail++;if(mpfr_cmp(m,minm)<0){mpfr_set(minm,m,MPFR_RNDN);mi=i;mj=j;wa=mpfr_get_d(A0,MPFR_RNDU);wb=mpfr_get_d(A1,MPFR_RNDU);}}printf("PSC MULTITIER t<=0.22 PREC=%d K=%d LBASE=%d LDEN=%d LCOUNT=%d ibox=[%d,%d) boxes=%d fail=%d\n",PREC,K,LBASE,LDEN,LCOUNT,ILO,IHI,(IHI-ILO)*LCOUNT,fail);printf("minimum_margin_lower=%.17g\n",mpfr_get_d(minm,MPFR_RNDD));printf("worst_t=[%.6f,%.6f] lambda=[%.4f,%.4f]\n",tlo(mi),thi(mi),(LBASE+mj)/(double)LDEN,(LBASE+mj+1)/(double)LDEN);printf("A0_upper=%.17g A1_upper=%.17g\n",wa,wb);printf("GRID_RESULT pass=%d\n",fail==0&&mpfr_cmp_ui(minm,0)>0);return fail?1:0;}
