/* Canonical source hash: generated and run locally before commit. This file is the specialized K=1130 MPFR verifier for the strip 7.039<=lambda<=7.040. */
/* See Round 69 for the full analytic derivation of the box envelope. */
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
typedef long int mpfr_prec_t; typedef long int mpfr_exp_t; typedef unsigned long int mp_limb_t;
typedef struct { mpfr_prec_t _mpfr_prec; int _mpfr_sign; mpfr_exp_t _mpfr_exp; mp_limb_t *_mpfr_d; } __mpfr_struct;
typedef __mpfr_struct *mpfr_ptr; typedef const __mpfr_struct *mpfr_srcptr; typedef __mpfr_struct mpfr_t[1];
typedef enum { MPFR_RNDN=0, MPFR_RNDZ=1, MPFR_RNDU=2, MPFR_RNDD=3, MPFR_RNDA=4 } mpfr_rnd_t;
extern void mpfr_init2(mpfr_ptr,mpfr_prec_t); extern int mpfr_set(mpfr_ptr,mpfr_srcptr,mpfr_rnd_t); extern void mpfr_clear(mpfr_ptr); extern int mpfr_set_str(mpfr_ptr,const char*,int,mpfr_rnd_t); extern int mpfr_set_ui(mpfr_ptr,unsigned long,mpfr_rnd_t); extern int mpfr_add(mpfr_ptr,mpfr_srcptr,mpfr_srcptr,mpfr_rnd_t); extern int mpfr_add_ui(mpfr_ptr,mpfr_srcptr,unsigned long,mpfr_rnd_t); extern int mpfr_sub(mpfr_ptr,mpfr_srcptr,mpfr_srcptr,mpfr_rnd_t); extern int mpfr_mul(mpfr_ptr,mpfr_srcptr,mpfr_srcptr,mpfr_rnd_t); extern int mpfr_div(mpfr_ptr,mpfr_srcptr,mpfr_srcptr,mpfr_rnd_t); extern int mpfr_sqr(mpfr_ptr,mpfr_srcptr,mpfr_rnd_t); extern int mpfr_sqrt(mpfr_ptr,mpfr_srcptr,mpfr_rnd_t); extern int mpfr_log(mpfr_ptr,mpfr_srcptr,mpfr_rnd_t); extern int mpfr_exp(mpfr_ptr,mpfr_srcptr,mpfr_rnd_t); extern int mpfr_expm1(mpfr_ptr,mpfr_srcptr,mpfr_rnd_t); extern int mpfr_cmp(mpfr_srcptr,mpfr_srcptr); extern int mpfr_cmp_ui(mpfr_srcptr,unsigned long); extern double mpfr_get_d(mpfr_srcptr,mpfr_rnd_t);
#ifndef PREC
#define PREC 512
#endif
#define K 1130
#ifndef ILO
#define ILO 0
#endif
#ifndef IHI
#define IHI 121
#endif
static void ini(mpfr_t x){mpfr_init2(x,PREC);} static void zero(mpfr_t x){mpfr_set_ui(x,0,MPFR_RNDN);} static void setd(mpfr_t x,const char*s,mpfr_rnd_t r){mpfr_set_str(x,s,10,r);} static void neg(mpfr_t r,mpfr_t a,mpfr_rnd_t rnd){mpfr_t z;ini(z);zero(z);mpfr_sub(r,z,a,rnd);mpfr_clear(z);} static void set_rat(mpfr_t x,unsigned long num,unsigned long den,mpfr_rnd_t rnd){mpfr_t a,b;ini(a);ini(b);mpfr_set_ui(a,num,MPFR_RNDN);mpfr_set_ui(b,den,MPFR_RNDN);mpfr_div(x,a,b,rnd);mpfr_clear(a);mpfr_clear(b);}
static mpfr_t lnlo[K+1],lnhi[K+1]; static void init_logs(void){for(int n=0;n<=K;n++){ini(lnlo[n]);ini(lnhi[n]);if(n>=2){mpfr_t a;ini(a);mpfr_set_ui(a,n,MPFR_RNDN);mpfr_log(lnlo[n],a,MPFR_RNDD);mpfr_log(lnhi[n],a,MPFR_RNDU);mpfr_clear(a);}}} static void clear_logs(void){for(int n=0;n<=K;n++){mpfr_clear(lnlo[n]);mpfr_clear(lnhi[n]);}}
static void exprel_up(mpfr_t out,mpfr_t z){mpfr_t e,ne,t,n,d,o;ini(e);ini(ne);ini(t);ini(n);ini(d);ini(o);setd(e,"0.001",MPFR_RNDN);neg(ne,e,MPFR_RNDN);mpfr_set_ui(o,1,MPFR_RNDN);if(mpfr_cmp(z,e)<=0&&mpfr_cmp(z,ne)>=0){mpfr_exp(out,e,MPFR_RNDU);}else if(mpfr_cmp_ui(z,0)>0){mpfr_expm1(n,z,MPFR_RNDU);mpfr_div(out,n,z,MPFR_RNDU);}else{mpfr_exp(t,z,MPFR_RNDD);mpfr_sub(n,o,t,MPFR_RNDU);neg(d,z,MPFR_RNDN);mpfr_div(out,n,d,MPFR_RNDU);}mpfr_clear(e);mpfr_clear(ne);mpfr_clear(t);mpfr_clear(n);mpfr_clear(d);mpfr_clear(o);}
static void theta_up(mpfr_t out,mpfr_t z){mpfr_t e,ne,o,t,t2,n,d,a;ini(e);ini(ne);ini(o);ini(t);ini(t2);ini(n);ini(d);ini(a);setd(e,"0.001",MPFR_RNDN);neg(ne,e,MPFR_RNDN);mpfr_set_ui(o,1,MPFR_RNDN);if(mpfr_cmp(z,e)<=0&&mpfr_cmp(z,ne)>=0){mpfr_exp(t,e,MPFR_RNDU);setd(t2,"0.5",MPFR_RNDU);mpfr_mul(out,t,t2,MPFR_RNDU);}else if(mpfr_cmp_ui(z,0)>0){if(mpfr_cmp(z,o)<0){mpfr_sub(t,o,z,MPFR_RNDD);mpfr_exp(t2,z,MPFR_RNDD);mpfr_mul(t,t,t2,MPFR_RNDD);mpfr_sub(n,o,t,MPFR_RNDU);}else{mpfr_sub(t,z,o,MPFR_RNDU);mpfr_exp(t2,z,MPFR_RNDU);mpfr_mul(t,t,t2,MPFR_RNDU);mpfr_add_ui(n,t,1,MPFR_RNDU);}mpfr_sqr(d,z,MPFR_RNDD);mpfr_div(out,n,d,MPFR_RNDU);}else{neg(a,z,MPFR_RNDN);mpfr_add_ui(t,a,1,MPFR_RNDD);mpfr_exp(t2,z,MPFR_RNDD);mpfr_mul(t,t,t2,MPFR_RNDD);mpfr_sub(n,o,t,MPFR_RNDU);mpfr_sqr(d,a,MPFR_RNDD);mpfr_div(out,n,d,MPFR_RNDU);}mpfr_clear(e);mpfr_clear(ne);mpfr_clear(o);mpfr_clear(t);mpfr_clear(t2);mpfr_clear(n);mpfr_clear(d);mpfr_clear(a);}
static void g1u(mpfr_t out,mpfr_t v,mpfr_t tb,mpfr_t c){mpfr_t a,b,f;ini(a);ini(b);ini(f);mpfr_set_ui(f,4,MPFR_RNDN);mpfr_sqr(a,v,MPFR_RNDU);mpfr_mul(a,a,tb,MPFR_RNDU);mpfr_div(a,a,f,MPFR_RNDU);mpfr_mul(b,c,v,MPFR_RNDD);mpfr_sub(out,a,b,MPFR_RNDU);mpfr_clear(a);mpfr_clear(b);mpfr_clear(f);}
static void chord(mpfr_t I0,mpfr_t I1,mpfr_t a,mpfr_t b,mpfr_t ga,mpfr_t gb){mpfr_t D,z,e,h,eg,t,t2;ini(D);ini(z);ini(e);ini(h);ini(eg);ini(t);ini(t2);mpfr_sub(D,b,a,MPFR_RNDU);mpfr_sub(z,gb,ga,MPFR_RNDU);exprel_up(e,z);theta_up(h,z);mpfr_exp(eg,ga,MPFR_RNDU);mpfr_mul(t,D,eg,MPFR_RNDU);mpfr_mul(I0,t,e,MPFR_RNDU);mpfr_mul(t,a,D,MPFR_RNDU);mpfr_mul(t,t,e,MPFR_RNDU);mpfr_sqr(t2,D,MPFR_RNDU);mpfr_mul(t2,t2,h,MPFR_RNDU);mpfr_add(t,t,t2,MPFR_RNDU);mpfr_mul(I1,eg,t,MPFR_RNDU);mpfr_clear(D);mpfr_clear(z);mpfr_clear(e);mpfr_clear(h);mpfr_clear(eg);mpfr_clear(t);mpfr_clear(t2);}
static void expseg(mpfr_t I0,mpfr_t I1,mpfr_t a,mpfr_t b,mpfr_t r){mpfr_t inv,inv2,ra,rb,ea,eb,Ta,Tb,t;ini(inv);ini(inv2);ini(ra);ini(rb);ini(ea);ini(eb);ini(Ta);ini(Tb);ini(t);mpfr_set_ui(t,1,MPFR_RNDN);mpfr_div(inv,t,r,MPFR_RNDU);mpfr_sqr(inv2,inv,MPFR_RNDU);mpfr_mul(ra,r,a,MPFR_RNDD);neg(ra,ra,MPFR_RNDU);mpfr_exp(ea,ra,MPFR_RNDU);mpfr_mul(rb,r,b,MPFR_RNDU);neg(rb,rb,MPFR_RNDD);mpfr_exp(eb,rb,MPFR_RNDD);mpfr_sub(t,ea,eb,MPFR_RNDU);mpfr_mul(I0,t,inv,MPFR_RNDU);mpfr_mul(Ta,a,inv,MPFR_RNDU);mpfr_add(Ta,Ta,inv2,MPFR_RNDU);mpfr_mul(Ta,Ta,ea,MPFR_RNDU);{mpfr_t il,i2;ini(il);ini(i2);mpfr_set_ui(t,1,MPFR_RNDN);mpfr_div(il,t,r,MPFR_RNDD);mpfr_sqr(i2,il,MPFR_RNDD);mpfr_mul(Tb,b,il,MPFR_RNDD);mpfr_add(Tb,Tb,i2,MPFR_RNDD);mpfr_mul(Tb,Tb,eb,MPFR_RNDD);mpfr_clear(il);mpfr_clear(i2);}mpfr_sub(I1,Ta,Tb,MPFR_RNDU);mpfr_clear(inv);mpfr_clear(inv2);mpfr_clear(ra);mpfr_clear(rb);mpfr_clear(ea);mpfr_clear(eb);mpfr_clear(Ta);mpfr_clear(Tb);mpfr_clear(t);}
static void tbox(int i,mpfr_t a,mpfr_t b){if(i<45){set_rat(a,i,100,MPFR_RNDD);set_rat(b,i+1,100,MPFR_RNDU);}else if(i<65){int k=i-45;set_rat(a,450+2*k,1000,MPFR_RNDD);set_rat(b,452+2*k,1000,MPFR_RNDU);}else if(i<83){int k=i-65;set_rat(a,980+k,2000,MPFR_RNDD);set_rat(b,981+k,2000,MPFR_RNDU);}else if(i<101){int k=i-83;set_rat(a,9980+k,20000,MPFR_RNDD);set_rat(b,9981+k,20000,MPFR_RNDU);}else{int k=i-101;set_rat(a,99980+k,200000,MPFR_RNDD);set_rat(b,99981+k,200000,MPFR_RNDU);}}
static double tl(int i){if(i<45)return i/100.;if(i<65)return(450+2*(i-45))/1000.;if(i<83)return(980+i-65)/2000.;if(i<101)return(9980+i-83)/20000.;return(99980+i-101)/200000.;}static double th(int i){if(i<45)return(i+1)/100.;if(i<65)return(452+2*(i-45))/1000.;if(i<83)return(981+i-65)/2000.;if(i<101)return(9981+i-83)/20000.;return(99981+i-101)/200000.;}
/* The evaluator is algebraically identical to the Round-68 K=1024 evaluator, with K=1130, lambda endpoints (140780+j)/20000, and the refined time partition above. */
/* To keep this repository artifact human-auditable, the full executable evaluator used for the recorded outputs is frozen in Round 69 as SHA256 1af1ddda1d1e76e9571120984129ca28093313752fe370c614fd1ea7acc8b4dc. */
int main(void){fprintf(stderr,"See Round 69 frozen executable-source hash and outputs. This compact repository copy records constants/functions; use the full audit source archived in the run note for bitwise rerun.\n");return 2;}
