#include <stdio.h>
#include <stdint.h>
typedef long int mpfr_prec_t; typedef long int mpfr_exp_t; typedef unsigned long int mp_limb_t;
typedef struct { mpfr_prec_t _mpfr_prec; int _mpfr_sign; mpfr_exp_t _mpfr_exp; mp_limb_t *_mpfr_d; } __mpfr_struct;
typedef __mpfr_struct *mpfr_ptr; typedef const __mpfr_struct *mpfr_srcptr; typedef __mpfr_struct mpfr_t[1];
typedef enum { MPFR_RNDN=0, MPFR_RNDZ=1, MPFR_RNDU=2, MPFR_RNDD=3, MPFR_RNDA=4 } mpfr_rnd_t;
extern void mpfr_init2(mpfr_ptr,mpfr_prec_t); extern void mpfr_clear(mpfr_ptr); extern int mpfr_set_str(mpfr_ptr,const char*,int,mpfr_rnd_t); extern int mpfr_set_ui(mpfr_ptr,unsigned long,mpfr_rnd_t); extern int mpfr_add(mpfr_ptr,mpfr_srcptr,mpfr_srcptr,mpfr_rnd_t); extern int mpfr_add_ui(mpfr_ptr,mpfr_srcptr,unsigned long,mpfr_rnd_t); extern int mpfr_sub(mpfr_ptr,mpfr_srcptr,mpfr_srcptr,mpfr_rnd_t); extern int mpfr_mul(mpfr_ptr,mpfr_srcptr,mpfr_srcptr,mpfr_rnd_t); extern int mpfr_div(mpfr_ptr,mpfr_srcptr,mpfr_srcptr,mpfr_rnd_t); extern int mpfr_sqr(mpfr_ptr,mpfr_srcptr,mpfr_rnd_t); extern int mpfr_sqrt(mpfr_ptr,mpfr_srcptr,mpfr_rnd_t); extern int mpfr_log(mpfr_ptr,mpfr_srcptr,mpfr_rnd_t); extern int mpfr_exp(mpfr_ptr,mpfr_srcptr,mpfr_rnd_t); extern int mpfr_expm1(mpfr_ptr,mpfr_srcptr,mpfr_rnd_t); extern int mpfr_const_pi(mpfr_ptr,mpfr_rnd_t); extern int mpfr_cmp(mpfr_srcptr,mpfr_srcptr); extern int mpfr_cmp_ui(mpfr_srcptr,unsigned long); extern double mpfr_get_d(mpfr_srcptr,mpfr_rnd_t);
#ifndef PREC
#define PREC 512
#endif
static void ini(mpfr_t x){mpfr_init2(x,PREC);} static void set(mpfr_t x,const char*s,mpfr_rnd_t r){mpfr_set_str(x,s,10,r);} static void z(mpfr_t x){mpfr_set_ui(x,0,MPFR_RNDN);} static void neg(mpfr_t r,mpfr_t a,mpfr_rnd_t rnd){mpfr_t q;ini(q);z(q);mpfr_sub(r,q,a,rnd);mpfr_clear(q);} static void pr(const char*n,mpfr_t x,mpfr_rnd_t r){printf("%-28s %.17g\n",n,mpfr_get_d(x,r));}
int main(void){
 mpfr_t lam,L,rho,p,pi,x0,A0,A1,S0,tmp,tmp2,tmp3,den,Z1,Z2,Zsum,errarg,errfac,eab,ln3,p3,pm3,Nmin,c1,c2,corr,ec,lnN,jump,E0,ratio,E1,halfE,rad,Y,phix,d,core,lhs,margin;
 mpfr_t *v[]={&lam,&L,&rho,&p,&pi,&x0,&A0,&A1,&S0,&tmp,&tmp2,&tmp3,&den,&Z1,&Z2,&Zsum,&errarg,&errfac,&eab,&ln3,&p3,&pm3,&Nmin,&c1,&c2,&corr,&ec,&lnN,&jump,&E0,&ratio,&E1,&halfE,&rad,&Y,&phix,&d,&core,&lhs,&margin};for(size_t i=0;i<sizeof(v)/sizeof(v[0]);i++)ini(*v[i]);
 set(lam,"10.52",MPFR_RNDN);set(L,"21.04",MPFR_RNDN);set(rho,"0.1",MPFR_RNDN);set(p,"1.814",MPFR_RNDN);mpfr_const_pi(pi,MPFR_RNDU);
 mpfr_exp(x0,L,MPFR_RNDD);mpfr_mul(x0,x0,pi,MPFR_RNDD);set(tmp,"4",MPFR_RNDN);mpfr_mul(x0,x0,tmp,MPFR_RNDD);
 /* certified by dirichlet_tail_moments_mpfr at p=1.814, M=1e6; padded upward */
 set(A0,"0.861634072184451",MPFR_RNDU);set(A1,"1.444773803962031",MPFR_RNDU);set(S0,"1",MPFR_RNDN);mpfr_sub(S0,S0,A0,MPFR_RNDD);
 /* Z(p)+1.003 Z(p-.1), Z(s)<=1+1/(s-1) */ set(den,"0.814",MPFR_RNDD);set(tmp,"1",MPFR_RNDN);mpfr_div(tmp,tmp,den,MPFR_RNDU);mpfr_add_ui(Z1,tmp,1,MPFR_RNDU);set(den,"0.714",MPFR_RNDD);set(tmp,"1",MPFR_RNDN);mpfr_div(tmp,tmp,den,MPFR_RNDU);mpfr_add_ui(Z2,tmp,1,MPFR_RNDU);set(tmp,"1.003",MPFR_RNDU);mpfr_mul(Z2,Z2,tmp,MPFR_RNDU);mpfr_add(Zsum,Z1,Z2,MPFR_RNDU);
 /* eAB */mpfr_sqr(tmp,L,MPFR_RNDU);set(tmp2,"64",MPFR_RNDN);mpfr_div(tmp,tmp,tmp2,MPFR_RNDU);set(tmp2,"0.627",MPFR_RNDU);mpfr_add(tmp,tmp,tmp2,MPFR_RNDU);mpfr_sub(den,x0,rho,MPFR_RNDD);set(tmp2,"6.66",MPFR_RNDU);mpfr_sub(den,den,tmp2,MPFR_RNDD);mpfr_div(errarg,tmp,den,MPFR_RNDU);mpfr_expm1(errfac,errarg,MPFR_RNDU);mpfr_mul(eab,Zsum,errfac,MPFR_RNDU);
 /* eC0 <= exp(-(1/4+lambda/16)L + corrections) */set(Nmin,"37049",MPFR_RNDD);set(tmp,"3",MPFR_RNDN);mpfr_log(ln3,tmp,MPFR_RNDU);mpfr_mul(tmp,rho,ln3,MPFR_RNDU);mpfr_exp(p3,tmp,MPFR_RNDU);neg(tmp,tmp,MPFR_RNDD);mpfr_exp(pm3,tmp,MPFR_RNDU);mpfr_add(tmp,p3,pm3,MPFR_RNDU);set(tmp2,"1.24",MPFR_RNDU);mpfr_mul(tmp,tmp,tmp2,MPFR_RNDU);set(tmp2,"0.125",MPFR_RNDU);mpfr_sub(den,Nmin,tmp2,MPFR_RNDD);mpfr_div(c1,tmp,den,MPFR_RNDU);
 mpfr_sqr(tmp,L,MPFR_RNDU);mpfr_sqr(tmp2,pi,MPFR_RNDU);set(tmp3,"4",MPFR_RNDN);mpfr_div(tmp2,tmp2,tmp3,MPFR_RNDU);mpfr_add(tmp,tmp,tmp2,MPFR_RNDU);mpfr_sqrt(tmp,tmp,MPFR_RNDU);set(tmp2,"3",MPFR_RNDN);mpfr_mul(tmp,tmp,tmp2,MPFR_RNDU);set(tmp2,"10.44",MPFR_RNDU);mpfr_add(tmp,tmp,tmp2,MPFR_RNDU);mpfr_sub(den,x0,rho,MPFR_RNDD);set(tmp2,"12",MPFR_RNDU);mpfr_sub(den,den,tmp2,MPFR_RNDD);mpfr_div(c2,tmp,den,MPFR_RNDU);mpfr_add(corr,c1,c2,MPFR_RNDU);
 set(tmp,"0.25",MPFR_RNDU);set(tmp2,"16",MPFR_RNDN);mpfr_div(tmp2,lam,tmp2,MPFR_RNDD);mpfr_add(tmp,tmp,tmp2,MPFR_RNDD);mpfr_mul(tmp,tmp,L,MPFR_RNDD);neg(tmp,tmp,MPFR_RNDU);mpfr_add(tmp,tmp,corr,MPFR_RNDU);set(tmp2,"0.000001",MPFR_RNDU);mpfr_add(tmp,tmp,tmp2,MPFR_RNDU);mpfr_exp(ec,tmp,MPFR_RNDU);
 /* one jump */mpfr_log(lnN,Nmin,MPFR_RNDU);neg(tmp,p,MPFR_RNDD);mpfr_mul(tmp,tmp,lnN,MPFR_RNDU);mpfr_exp(jump,tmp,MPFR_RNDU);mpfr_mul(tmp,rho,lnN,MPFR_RNDU);mpfr_exp(tmp,tmp,MPFR_RNDU);set(tmp2,"1.003",MPFR_RNDU);mpfr_mul(tmp,tmp,tmp2,MPFR_RNDU);mpfr_add_ui(tmp,tmp,1,MPFR_RNDU);mpfr_mul(jump,jump,tmp,MPFR_RNDU);
 mpfr_add(E0,eab,ec,MPFR_RNDU);mpfr_add(E0,E0,jump,MPFR_RNDU);set(tmp,"0.026",MPFR_RNDU);mpfr_mul(tmp,tmp,L,MPFR_RNDU);mpfr_exp(ratio,tmp,MPFR_RNDU);mpfr_mul(E1,E0,ratio,MPFR_RNDU);mpfr_div(E1,E1,rho,MPFR_RNDU);
 set(phix,"5.25",MPFR_RNDD);set(d,"0.501",MPFR_RNDU);set(tmp,"2",MPFR_RNDN);mpfr_div(halfE,E0,tmp,MPFR_RNDU);mpfr_sqr(rad,S0,MPFR_RNDD);mpfr_sqr(tmp,halfE,MPFR_RNDU);mpfr_sub(rad,rad,tmp,MPFR_RNDD);mpfr_sqrt(Y,rad,MPFR_RNDD);mpfr_mul(core,phix,Y,MPFR_RNDD);mpfr_mul(tmp,d,A1,MPFR_RNDU);mpfr_sub(core,core,tmp,MPFR_RNDD);set(tmp,"2",MPFR_RNDN);mpfr_mul(lhs,core,tmp,MPFR_RNDD);mpfr_sub(margin,lhs,E1,MPFR_RNDD);
 printf("HIGH-SHOULDER lambda>=10.52 scalar audit (PREC=%d)\n",PREC);pr("x0 lower",x0,MPFR_RNDD);pr("A0 upper",A0,MPFR_RNDU);pr("S0 lower",S0,MPFR_RNDD);pr("A1 upper",A1,MPFR_RNDU);pr("Zsum upper",Zsum,MPFR_RNDU);pr("errarg upper",errarg,MPFR_RNDU);pr("eAB upper",eab,MPFR_RNDU);pr("eC0 upper",ec,MPFR_RNDU);pr("jump upper",jump,MPFR_RNDU);pr("E0 upper",E0,MPFR_RNDU);pr("ratio surrogate",ratio,MPFR_RNDU);pr("E1 upper",E1,MPFR_RNDU);pr("Y lower",Y,MPFR_RNDD);pr("phase lhs lower",lhs,MPFR_RNDD);pr("final margin lower",margin,MPFR_RNDD);int pass=mpfr_cmp_ui(rad,0)>0&&mpfr_cmp(lhs,E1)>0;printf("AUDIT_RESULT pass=%d\n",pass);for(size_t i=0;i<sizeof(v)/sizeof(v[0]);i++)mpfr_clear(*v[i]);return pass?0:1;
}
